"""
Synthesis nodes for manuscript generation and strategic triage.

This module contains nodes responsible for:
- Synthesizing verified claims into manuscript blocks (synthesizer_node)
- Strategic triage for summary vs detail (lead_counsel_node)
- Mathematical autoformalization (logician_node)
"""

import json
from typing import Dict, Any, List

from ...shared.logger import get_logger
from ..state import PhaseEnum, ResearchState
from ..telemetry import trace_node
from ..prompts import get_active_prompt_with_meta, DEFAULT_SYNTHESIZER_PROMPT
from .base import wrap_prompt_with_context
from .nodes import validate_state_schema, hydrate_project_context

logger = get_logger("orchestrator", __name__)


@trace_node
def synthesizer_node(state: ResearchState) -> ResearchState:
    """Synthesize verified claims into manuscript blocks with citation integrity guard.
    
    Enforces that each paragraph includes at least one claim binding reference.
    Rejects blocks without bindings in conservative mode, warns in exploratory.
    """
    state = validate_state_schema(state)
    state = hydrate_project_context(state)
    
    job_id = state.get("jobId") or state.get("job_id")
    project_context = state.get("project_context")
    rigor_level = state.get("rigor_level") or (project_context or {}).get("rigor_level", "exploratory")
    
    logger.info("Synthesizer node executed", extra={"payload": {"job_id": job_id}})
    
    # Get vocabulary guard for applying constraints
    try:
        from ...shared.vocab_guard import get_vocab_guard
        vocab_guard = get_vocab_guard()
    except Exception as e:
        logger.warning(f"Failed to load vocab guard: {e}", exc_info=True)
        vocab_guard = None
    
    extracted = state.get("extracted_json") or {}
    triples = extracted.get("triples") if isinstance(extracted, dict) else []
    synthesis_text = state.get("synthesis")
    
    # Fetch prompt from Prompt Registry (with fallback to factory default)
    system_template, prompt_meta = get_active_prompt_with_meta("vyasa-synthesizer", DEFAULT_SYNTHESIZER_PROMPT)
    
    # Record prompt usage in state
    prompt_manifest = state.get("prompt_manifest", {})
    prompt_manifest["synthesizer"] = prompt_meta.model_dump(mode="python")
    state["prompt_manifest"] = prompt_manifest
    
    # Wrap prompt with context (apply AFTER fetching from Opik)
    system_prompt = wrap_prompt_with_context(state, system_template)
    
    # Get available claim IDs from triples
    available_claim_ids = []
    if isinstance(triples, list):
        for triple in triples:
            if isinstance(triple, dict):
                claim_id = triple.get("claim_id") or triple.get("_id") or triple.get("id")
                if claim_id:
                    available_claim_ids.append(str(claim_id))
    
    # Prepare claims as JSON for LLM input
    claims_json = []
    if isinstance(triples, list):
        for triple in triples:
            if isinstance(triple, dict):
                claim_entry = {
                    "claim_id": triple.get("claim_id") or triple.get("_id") or "",
                    "subject": triple.get("subject", ""),
                    "predicate": triple.get("predicate", ""),
                    "object": triple.get("object", ""),
                    "claim_text": triple.get("claim_text") or f"{triple.get('subject', '')} {triple.get('predicate', '')} {triple.get('object', '')}",
                }
                claims_json.append(claim_entry)
    
    # Add instruction to include claim bindings in output
    binding_instruction = f"""
CRITICAL OUTPUT REQUIREMENT:
You MUST include claim bindings in your output. Use one of these formats:

1. Inline references: End sentences with [[claim_id]] markers.
   Example: "The study found significant results [[claim_123]]."

2. Explicit claim_ids array: Include a JSON structure with claim_ids.
   Example: {{"text": "...", "claim_ids": ["claim_123", "claim_456"]}}

Available Claims (with IDs):
{json.dumps(claims_json[:20], indent=2) if claims_json else "[]"}

Every paragraph MUST reference at least one claim_id from the list above.
"""
    
    system_prompt = f"{system_prompt}\n\n{binding_instruction}"
    
    # If synthesis_text exists, it means it was generated by a previous step
    # Otherwise, generate it using LLM with vocab guard constraints
    if not synthesis_text:
        # For now, generate a simple summary (placeholder implementation)
        # When fully implemented, this would call llm_client.chat() with vocab_guard constraints
        # The LLM should be instructed to include claim bindings
        synthesis_text = f"Synthesized summary: processed {len(triples) if isinstance(triples, list) else 0} triples."
        
        # Example of how vocab_guard would be applied before LLM call:
        # if vocab_guard:
        #     system_prompt = vocab_guard.apply_constraints(system_prompt)
        # Then use the modified system_prompt in the llm_client.chat() call
    
    # Parse synthesis_text to extract manuscript blocks
    # For now, assume synthesis_text is a single block or JSON array of blocks
    manuscript_blocks = []
    try:
        # Try to parse as JSON array
        parsed = json.loads(synthesis_text) if isinstance(synthesis_text, str) and synthesis_text.strip().startswith("[") else synthesis_text
        if isinstance(parsed, list):
            manuscript_blocks = parsed
        else:
            # Single block - create block structure
            block_id = f"block_{job_id or 'default'}_0"
            manuscript_blocks = [{
                "block_id": block_id,
                "text": synthesis_text,
                "content": synthesis_text,
                "claim_ids": [],  # Will be extracted below
                "citation_keys": [],
            }]
    except (json.JSONDecodeError, AttributeError):
        # Not JSON, treat as single block
        block_id = f"block_{job_id or 'default'}_0"
        manuscript_blocks = [{
            "block_id": block_id,
            "text": synthesis_text,
            "content": synthesis_text,
            "claim_ids": [],
            "citation_keys": [],
        }]
    
    # Extract claim_ids from inline references and add to block metadata
    from ..validators.citation_integrity import extract_claim_ids_from_text
    
    for block in manuscript_blocks:
        block_text = block.get("text") or block.get("content", "")
        inline_claim_ids = extract_claim_ids_from_text(block_text)
        explicit_claim_ids = block.get("claim_ids", [])
        # Combine and deduplicate
        all_claim_ids = list(set(explicit_claim_ids + inline_claim_ids))
        block["claim_ids"] = all_claim_ids
    
    # Citation integrity validation: validate that blocks include claim bindings
    from ..validators.citation_integrity import validate_manuscript_blocks
    
    valid_blocks, validation_errors = validate_manuscript_blocks(
        blocks=manuscript_blocks,
        available_claim_ids=available_claim_ids,
        rigor_level=rigor_level,
    )
    
    # In conservative mode, reject if validation fails
    if rigor_level == "conservative" and validation_errors:
        logger.error(
            "Synthesizer: Blocks rejected - citation integrity validation failed",
            extra={"payload": {"errors": validation_errors, "block_count": len(manuscript_blocks)}}
        )
        return {
            "synthesis": "",
            "synthesis_error": f"Citation integrity validation failed: {'; '.join(validation_errors)}",
            "manuscript_blocks": [],
            "phase": PhaseEnum.SYNTHESIZING.value,
        }
    
    # In exploratory mode, warn but allow
    if rigor_level == "exploratory" and validation_errors:
        logger.warning(
            "Synthesizer: Blocks have citation integrity issues (exploratory mode allows)",
            extra={"payload": {"errors": validation_errors, "block_count": len(manuscript_blocks)}}
        )
    
    # Update state with validated blocks
    # Note: Tone guard will run AFTER this (in workflow), so we don't do tone rewrite here
    return {
        "synthesis": synthesis_text,
        "manuscript_blocks": valid_blocks,
        "phase": PhaseEnum.SYNTHESIZING.value,
    }


@trace_node
def lead_counsel_node(state: ResearchState) -> ResearchState:
    """Strategic triage: choose summary vs detail based on kernel overlap and new primitives."""
    state = validate_state_schema(state)
    summary = state.get("librarian_summary") or state.get("summary") or ""
    project_kernel = (
        state.get("project_kernel")
        or (state.get("project_context") or {}).get("thesis")
        or ""
    )
    triples = []
    extracted = state.get("extracted_json") or {}
    if isinstance(extracted, dict):
        triples = extracted.get("triples") or []

    def _tokenize(text: str) -> List[str]:
        return [t.lower() for t in text.replace("\n", " ").split() if t]

    kernel_tokens = set(_tokenize(project_kernel))
    summary_tokens = set(_tokenize(summary))

    redundant = sorted(list(summary_tokens & kernel_tokens))

    new_primitives: List[str] = []
    for t in triples:
        if not isinstance(t, dict):
            continue
        for part in ("subject", "object", "predicate"):
            val = t.get(part)
            if isinstance(val, str):
                for token in _tokenize(val):
                    if token and token not in kernel_tokens:
                        new_primitives.append(token)

    presentation = "DETAIL" if new_primitives else "SUMMARIZE"
    triage = {
        "redundant": redundant,
        "unique": new_primitives,
        "presentation": presentation,
    }
    return {"lead_counsel": triage}


@trace_node
def logician_node(state: ResearchState) -> ResearchState:
    """Autoformalization using the math sandbox."""
    state = validate_state_schema(state)
    latex = state.get("latex_formula") or state.get("logician_input") or ""
    try:
        from .tools.math_sandbox import MathSandbox  # Local import to avoid optional dep failures at import time

        sandbox = MathSandbox()
        result = sandbox.execute_symbolic(latex) if latex else {"error": "no_formula"}
        result["tool_used"] = "math_sandbox"
    except Exception as exc:  # noqa: BLE001
        result = {"error": f"math_sandbox_unavailable:{exc}"}
    return {"logic_validation": result}

