#!/usr/bin/env bash
set -euo pipefail

# ==========================================
# Project Vyasa - System Bootstrapping Script
# ------------------------------------------
# Description : Sequential startup of Vyasa services on DGX Spark.
# Dependencies: docker, docker compose, curl, openssl
# Usage       : ./scripts/init_vyasa.sh
# [Decision] Credentials are auto-generated by default to prevent hardcoded leaks;
#            users can manually override in deploy/.env after the first run.
# ==========================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOY_DIR="$PROJECT_ROOT/deploy"
. "$SCRIPT_DIR/lib/env.sh"
load_env_defaults

echo "=========================================="
echo "Project Vyasa - System Bootstrapping"
echo "DGX Spark (GB10) Startup Sequence"
echo "=========================================="
echo ""

# ============================================
# Step 1: Source Secrets and Environment
# ============================================
echo "Step 1: Loading secrets and environment variables..."

SECRETS_FILE="$DEPLOY_DIR/secrets.env"
ENV_FILE="$DEPLOY_DIR/.env"

if [ -f "$SECRETS_FILE" ]; then
  echo "  Sourcing $SECRETS_FILE..."
  set -a  # Export all variables
  source "$SECRETS_FILE"
  set +a
  echo "  ✓ Secrets loaded"
else
  echo "  ⚠ Warning: $SECRETS_FILE not found. Using environment defaults."
fi

# Ensure .env exists and auto-generate missing secrets
touch "$ENV_FILE"

ensure_env_secret() {
  local var_name="$1"
  local env_file="$2"
  local current
  current="$(grep -E "^${var_name}=" "$env_file" 2>/dev/null | cut -d'=' -f2- || true)"
  if [ -z "$current" ]; then
    local generated
    generated=$(openssl rand -hex 24)
    echo "${var_name}=${generated}" >> "$env_file"
    echo "  • Generated ${var_name}"
  fi
}

ensure_env_secret "ARANGODB_PASSWORD" "$ENV_FILE"
ensure_env_secret "ARANGO_ROOT_PASSWORD" "$ENV_FILE"
ensure_env_secret "INTERNAL_AUTH_TOKEN" "$ENV_FILE"
ensure_env_secret "CONSOLE_SECRET" "$ENV_FILE"
ensure_env_secret "CONSOLE_PASSWORD" "$ENV_FILE"

# Source .env after generation
echo "  Sourcing $ENV_FILE..."
set -a
source "$ENV_FILE"
set +a
echo "  ✓ Environment variables loaded"

echo ""

# ============================================
# Step 2: Start Graph and Vector Services
# ============================================
echo "Step 2: Starting Graph (ArangoDB) and Vector (Qdrant) services..."

cd "$DEPLOY_DIR"

# Start only graph and vector services first
docker compose up -d vyasa-memory vyasa-qdrant

echo "  Waiting for Graph and Vector to become healthy..."
max_attempts=30
attempt=1

while [ $attempt -le $max_attempts ]; do
  # Check ArangoDB
  if curl -s -f "http://localhost:8529/_api/version" > /dev/null 2>&1; then
    # Check Qdrant
    if curl -s -f "http://localhost:6333/healthz" > /dev/null 2>&1; then
      echo "  ✓ Graph and Vector services are healthy"
      break
    fi
  fi
  
  if [ $attempt -eq $max_attempts ]; then
    echo "  ✗ Timeout waiting for Graph/Vector services"
    exit 1
  fi
  
  echo "  Waiting... (attempt $attempt/$max_attempts)"
  attempt=$((attempt + 1))
  sleep 2
done

echo ""

# ============================================
# Step 3: Start Cortex Models and Wait for Readiness
# ============================================
echo "Step 3: Starting Cortex models (Brain/Worker/Vision)..."

docker compose up -d cortex-brain cortex-worker cortex-vision

echo "  Waiting for Cortex Worker model to be ready..."
max_attempts=60  # Models take longer to load
attempt=1

while [ $attempt -le $max_attempts ]; do
  # Poll the Worker's /v1/models endpoint (SGLang OpenAI-compatible API)
  if curl -s -f "http://localhost:30001/v1/models" > /dev/null 2>&1; then
    echo "  ✓ Cortex Worker model is ready"
    break
  fi
  
  if [ $attempt -eq $max_attempts ]; then
    echo "  ✗ Timeout waiting for Cortex Worker model"
    echo "  Check logs: docker compose logs cortex-worker"
    exit 1
  fi
  
  if [ $((attempt % 10)) -eq 0 ]; then
    echo "  Still waiting... (attempt $attempt/$max_attempts)"
  fi
  attempt=$((attempt + 1))
  sleep 3
done

echo ""

# ============================================
# Step 4: Start Orchestrator
# ============================================
echo "Step 4: Starting Orchestrator (depends on Cortex models)..."

docker compose up -d vyasa-orchestrator

echo "  Waiting for Orchestrator to become healthy..."
max_attempts=30
attempt=1

while [ $attempt -le $max_attempts ]; do
  if curl -s -f "http://localhost:8000/health" > /dev/null 2>&1; then
    echo "  ✓ Orchestrator is healthy"
    break
  fi
  
  if [ $attempt -eq $max_attempts ]; then
    echo "  ✗ Timeout waiting for Orchestrator"
    echo "  Check logs: docker compose logs vyasa-orchestrator"
    exit 1
  fi
  
  echo "  Waiting... (attempt $attempt/$max_attempts)"
  attempt=$((attempt + 1))
  sleep 2
done

echo ""

# ============================================
# Step 5: Start Console
# ============================================
echo "Step 5: Starting Console (depends on Orchestrator)..."

docker compose up -d vyasa-console

echo "  Waiting for Console to become ready..."
max_attempts=30
attempt=1

while [ $attempt -le $max_attempts ]; do
  if curl -s -f "http://localhost:3000" > /dev/null 2>&1; then
    echo "  ✓ Console is ready"
    break
  fi
  
  if [ $attempt -eq $max_attempts ]; then
    echo "  ⚠ Console may still be starting. Check: http://localhost:3000"
  else
    echo "  Waiting... (attempt $attempt/$max_attempts)"
    attempt=$((attempt + 1))
    sleep 2
  fi
done

echo ""

# ============================================
# Summary
# ============================================
echo "=========================================="
echo "Project Vyasa - Startup Complete"
echo "=========================================="
echo ""
echo "Services Status:"
echo "  Graph (ArangoDB):    http://localhost:8529"
echo "  Vector (Qdrant):      http://localhost:6333"
echo "  Brain (Cortex):       http://localhost:30000"
echo "  Worker (Cortex):      http://localhost:30001"
echo "  Vision (Cortex):      http://localhost:30002"
echo "  Orchestrator:         http://localhost:8000"
echo "  Console:              http://localhost:3000"
echo ""
echo "Next steps:"
echo "  1. Access Console: http://localhost:3000"
echo "  2. Create a project with Thesis and Research Questions"
echo "  3. Upload PDF documents to begin extraction"
echo ""
