#!/usr/bin/env bash
#
# Project Vyasa - Environment Bootstrap
# Purpose: Generate secrets without mutating deploy/.env or .env.example.
# Output: deploy/.secrets.env (git-ignored)
#
# [Decision] Credentials are auto-generated by default to prevent hardcoded leaks;
# override manually in .env if needed.
#
# Usage:
#   ./scripts/init_vyasa.sh --bootstrap-secrets
#   ./scripts/init_vyasa.sh --help

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOY_DIR="$PROJECT_ROOT/deploy"
SECRETS_FILE="$DEPLOY_DIR/.secrets.env"

usage() {
  cat <<EOF
Usage: $0 [--bootstrap-secrets] [--configure-nvidia] [--check-model-cache] [--skip-model-cache] [--force]
  --bootstrap-secrets   Generate secrets into deploy/.secrets.env (idempotent)
  --configure-nvidia     Configure NVIDIA Container Toolkit for Docker (requires sudo)
  --check-model-cache    Verify model cache coverage and offer to preload missing models
  --skip-model-cache     Skip model cache check during init
  --force                Overwrite deploy/.secrets.env even if it exists
  --help                 Show this help

Notes:
  - deploy/.env and deploy/.env.example are never modified by this script.
  - ARANGO_ROOT_PASSWORD is canonical for ArangoDB auth; ARANGODB_PASSWORD
    is read only for legacy compatibility.
  - --configure-nvidia must be run with sudo to modify Docker configuration.
EOF
}

BOOTSTRAP=false
CONFIGURE_NVIDIA=false
CHECK_MODEL_CACHE=false
SKIP_MODEL_CACHE=false
FORCE=false

while [ $# -gt 0 ]; do
  case "$1" in
    --bootstrap-secrets) BOOTSTRAP=true ;;
    --configure-nvidia) CONFIGURE_NVIDIA=true ;;
    --check-model-cache) CHECK_MODEL_CACHE=true ;;
    --skip-model-cache) SKIP_MODEL_CACHE=true ;;
    --force) FORCE=true ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
  shift
done

ensure_writable_dir() {
  local dir="$1"
  if [ ! -d "$dir" ]; then
    mkdir -p "$dir"
  fi
}

append_kv() {
  local key="$1"; local value="$2"; local target="$3"
  if ! grep -Eq "^${key}=" "$target" 2>/dev/null; then
    echo "${key}=${value}" >> "$target"
  fi
}

generate_secret() {
  openssl rand -hex 24
}

bootstrap_secrets() {
  ensure_writable_dir "$DEPLOY_DIR"

  # Load .env file if it exists (to read user-provided passwords)
  local env_file="$DEPLOY_DIR/.env"
  if [ -f "$env_file" ]; then
    # Source .env to load CONSOLE_PASSWORD and other vars (without exporting to avoid side effects)
    set -a
    source "$env_file" 2>/dev/null || true
    set +a
  fi

  # Prevent accidental rotation if volumes already exist (Arango lockout protection)
  local arango_data="/raid/vyasa/arangodb"
  local arango_has_data="false"
  if [ -d "$arango_data" ] && [ "$(find "$arango_data" -mindepth 1 -maxdepth 1 | wc -l)" -gt 0 ]; then
    arango_has_data="true"
  fi

  if [ -f "$SECRETS_FILE" ] && ! $FORCE; then
    echo "deploy/.secrets.env already exists. Use --force to regenerate."
    return
  fi

  # Start fresh if forcing; otherwise create if missing
  : > "$SECRETS_FILE"

  # Canonical secrets
  local arango_pw=""
  if [ -n "${ARANGO_ROOT_PASSWORD:-}" ]; then
    arango_pw="$ARANGO_ROOT_PASSWORD"
  elif [ -n "${ARANGODB_PASSWORD:-}" ]; then
    arango_pw="$ARANGODB_PASSWORD"
  fi

  if [ -z "$arango_pw" ]; then
    if [ "$arango_has_data" = "true" ]; then
      echo "ArangoDB data exists at $arango_data; not generating ARANGO_ROOT_PASSWORD to avoid lockout."
      echo "Add ARANGO_ROOT_PASSWORD to deploy/.secrets.env manually to match the existing volume."
    else
      arango_pw="$(generate_secret)"
    fi
  fi

  if [ -n "$arango_pw" ]; then
    append_kv "ARANGO_ROOT_PASSWORD" "$arango_pw" "$SECRETS_FILE"
  fi

  # Console / NextAuth secrets
  # Prefer CONSOLE_PASSWORD from .env if set, otherwise generate
  append_kv "CONSOLE_PASSWORD" "${CONSOLE_PASSWORD:-$(generate_secret)}" "$SECRETS_FILE"
  append_kv "CONSOLE_SECRET" "${CONSOLE_SECRET:-$(generate_secret)}" "$SECRETS_FILE"
  append_kv "NEXTAUTH_SECRET" "${NEXTAUTH_SECRET:-$(generate_secret)}" "$SECRETS_FILE"

  # Qdrant API key (optional; generate if empty)
  append_kv "QDRANT_API_KEY" "${QDRANT_API_KEY:-$(generate_secret)}" "$SECRETS_FILE"

  echo "Secrets written to $SECRETS_FILE"
}

configure_nvidia_runtime() {
  # Check if nvidia-ctk is available
  if ! command -v nvidia-ctk >/dev/null 2>&1; then
    echo "Error: nvidia-ctk not found. Install NVIDIA Container Toolkit first:"
    echo "  sudo apt-get install -y nvidia-container-toolkit"
    return 1
  fi

  # Check if already configured (verify Docker actually sees it, not just config file)
  # Use sudo docker info if we're running as root, otherwise regular docker info
  DOCKER_INFO_CMD="docker info"
  if [ "$EUID" -eq 0 ]; then
    DOCKER_INFO_CMD="docker info"
  fi
  
  if $DOCKER_INFO_CMD 2>/dev/null | grep -qiE "(runtimes.*nvidia|nvidia.*runtime)" || \
     [ -f /etc/docker/daemon.json ] && grep -q "nvidia" /etc/docker/daemon.json 2>/dev/null; then
    # Double-check Docker actually recognizes it
    if $DOCKER_INFO_CMD 2>/dev/null | grep -qiE "runtimes.*nvidia"; then
      echo "NVIDIA Container Toolkit is already configured for Docker."
      echo "Runtime detected in docker info output."
      return 0
    else
      echo "Warning: NVIDIA runtime is in daemon.json but Docker doesn't recognize it."
      echo "Docker may need to be restarted. Proceeding with restart..."
      # Fall through to restart Docker
    fi
  fi

  # Check if running with sudo
  if [ "$EUID" -ne 0 ]; then
    echo "Error: --configure-nvidia requires sudo privileges."
    echo "Please run: sudo $0 --configure-nvidia"
    return 1
  fi

  echo "Configuring NVIDIA Container Toolkit for Docker..."
  
  # Configure the runtime
  if nvidia-ctk runtime configure --runtime=docker; then
    echo "NVIDIA runtime configured successfully."
  else
    echo "Error: Failed to configure NVIDIA runtime."
    return 1
  fi

  # Restart Docker
  echo "Restarting Docker to apply configuration..."
  if systemctl restart docker; then
    echo "Docker restarted successfully."
  else
    echo "Warning: Failed to restart Docker. Please restart manually:"
    echo "  sudo systemctl restart docker"
    return 1
  fi

  # Verify configuration
  sleep 2
  if docker info 2>/dev/null | grep -qi "nvidia"; then
    echo "✓ NVIDIA Container Toolkit is now configured and active."
    return 0
  else
    echo "Warning: Configuration applied but verification failed."
    echo "Please check Docker logs: sudo journalctl -u docker -n 50"
    return 1
  fi
}

load_model_env() {
  local env_file="$DEPLOY_DIR/.env"
  local secrets_file="$DEPLOY_DIR/.secrets.env"
  if [ -f "$env_file" ]; then
    set -a
    # shellcheck disable=SC1090
    source "$env_file" 2>/dev/null || true
    set +a
  fi
  if [ -f "$secrets_file" ]; then
    set -a
    # shellcheck disable=SC1090
    source "$secrets_file" 2>/dev/null || true
    set +a
  fi
}

has_hf_cache() {
  local model_id="$1"
  local cache_dir="/raid/vyasa/hf_cache"
  local safe="${model_id//\//--}"
  local roots=("$cache_dir" "$cache_dir/hub")

  for root in "${roots[@]}"; do
    local repo_root="$root/models--$safe"
    local snap_dir="$repo_root/snapshots"
    if [ -d "$snap_dir" ]; then
      if find "$snap_dir" -type f -maxdepth 3 -print -quit 2>/dev/null | grep -q .; then
        return 0
      fi
    fi
  done
  return 1
}

has_ngc_embedder_cache() {
  local cache_dir="/raid/vyasa/hf_cache"
  local base_dir="$cache_dir/nvidia/nv-embedqa-e5-v5"
  if [ -d "$base_dir" ]; then
    if find "$base_dir" -type f -print -quit 2>/dev/null | grep -q .; then
      return 0
    fi
  fi
  return 1
}

check_model_cache() {
  load_model_env

  local text_model="${TEXT_MODEL_ID:-nvidia/Llama-3_3-Nemotron-Super-49B-v1_5}"
  local vision_model="${VISION_MODEL_ID:-Qwen/Qwen2-VL-7B-Instruct}"
  local embedder_model="${EMBEDDER_MODEL_ID:-nvidia/nv-embedqa-e5-v5}"
  local reranker_model="${RERANKER_MODEL_ID:-nvidia/llama-3.2-nv-rerankqa-1b-v2}"

  local missing=()

  if ! has_hf_cache "$text_model"; then
    missing+=("$text_model")
  fi
  if ! has_hf_cache "$vision_model"; then
    missing+=("$vision_model")
  fi
  if ! has_hf_cache "$reranker_model"; then
    missing+=("$reranker_model")
  fi

  if [ "$embedder_model" = "nvidia/nv-embedqa-e5-v5" ]; then
    if ! has_ngc_embedder_cache; then
      missing+=("$embedder_model (NVIDIA)")
    fi
  else
    if ! has_hf_cache "$embedder_model"; then
      missing+=("$embedder_model")
    fi
  fi

  if [ "${#missing[@]}" -eq 0 ]; then
    echo "✓ Model cache looks complete."
    return 0
  fi

  echo "⚠️  Missing model cache entries:"
  for model in "${missing[@]}"; do
    echo "  - $model"
  done

  echo ""
  read -r -p "Run model preload now? (scripts/preload_all_models.sh) [y/N] " response
  if [[ "$response" =~ ^[Yy]$ ]]; then
    "$PROJECT_ROOT/scripts/preload_all_models.sh"
  else
    echo "Skipping model preload. You can run it later:"
    echo "  $PROJECT_ROOT/scripts/preload_all_models.sh"
  fi
}

if $BOOTSTRAP; then
  bootstrap_secrets
  if ! $SKIP_MODEL_CACHE; then
    check_model_cache
  fi
fi

if $CONFIGURE_NVIDIA; then
  configure_nvidia_runtime
fi

if $CHECK_MODEL_CACHE; then
  check_model_cache
fi

if ! $BOOTSTRAP && ! $CONFIGURE_NVIDIA && ! $CHECK_MODEL_CACHE; then
  usage
fi
