#!/bin/bash
#
# Project Vyasa - Preflight Check (DGX Spark)
# Description : Validates hardware, memory, config, and ports before launch.
# Dependencies: nvidia-smi, curl, free, openssl, docker (optional), nc
# Usage       : ./scripts/preflight_check.sh
# [Decision] Credentials are auto-generated by default to prevent hardcoded leaks; users can override deploy/.env after first run.
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Status tracking
CHECKS_PASSED=0
CHECKS_FAILED=0
WARNINGS=0

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOY_DIR="$PROJECT_ROOT/deploy"
ENV_FILE="$DEPLOY_DIR/.env"
SECRETS_FILE="$DEPLOY_DIR/.secrets.env"
. "$SCRIPT_DIR/lib/env.sh"
load_env_defaults

# Load environment files without mutating them
load_env_file() {
  local file="$1"
  if [ -f "$file" ]; then
    set -a
    # shellcheck source=/dev/null
    source "$file"
    set +a
  fi
}

load_env_file "$ENV_FILE"
load_env_file "$SECRETS_FILE"

echo "=========================================="
echo "Project Vyasa - Preflight Check"
echo "DGX Spark (GB10) Validation"
echo "=========================================="
echo ""

# ============================================
# Check 0: Python runtime imports (a2wsgi, nvidia_smi)
# ============================================
echo -n "Checking Python import readiness (a2wsgi, nvidia_smi)... "
if python3 - <<'PY' >/dev/null 2>&1
import a2wsgi  # noqa: F401
import nvidia_smi  # noqa: F401
PY
then
  echo -e "${GREEN}PASS${NC}"
  ((CHECKS_PASSED++))
else
  echo -e "${RED}FAIL${NC}"
  echo "  Missing python deps (a2wsgi or nvidia-ml-py)."
  echo "  Remediation: pip install -r requirements.txt"
  ((CHECKS_FAILED++))
fi
echo ""

# ============================================
# Check 1: NVIDIA GPU Detection (GB10 Superchip)
# ============================================
echo -n "Checking NVIDIA GB10 superchip detection... "

if ! command -v nvidia-smi &> /dev/null; then
    echo -e "${RED}FAIL${NC}"
    echo "  Error: nvidia-smi not found. NVIDIA drivers may not be installed."
    ((CHECKS_FAILED++))
else
    # Check if nvidia-smi can see any GPUs
    GPU_COUNT=$(nvidia-smi --list-gpus 2>/dev/null | wc -l || echo "0")
    
    if [ "$GPU_COUNT" -eq "0" ]; then
        echo -e "${RED}FAIL${NC}"
        echo "  Error: nvidia-smi cannot detect any GPUs."
        echo "  Ensure NVIDIA drivers are installed and GB10 is properly connected."
        ((CHECKS_FAILED++))
    else
        # Check for GB10-specific identifiers
        # GB10 may show as "Grace Hopper" or "GH200" in nvidia-smi
        GPU_INFO=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -n1 || echo "")
        
        if echo "$GPU_INFO" | grep -qiE "(Grace|Hopper|GH200|GB10|Blackwell)"; then
            echo -e "${GREEN}PASS${NC}"
            echo "  Detected: $GPU_INFO"
            echo "  GPU Count: $GPU_COUNT"
            ((CHECKS_PASSED++))
        else
            echo -e "${YELLOW}WARN${NC}"
            echo "  Warning: GPU detected but may not be GB10 superchip."
            echo "  GPU Info: $GPU_INFO"
            echo "  Continuing with validation..."
            ((WARNINGS++))
            ((CHECKS_PASSED++))
        fi
    fi
fi
echo ""

# ============================================
# Check 2: Unified Memory Verification & 24GB Headroom
# ============================================
echo -n "Checking unified memory (minimum 120GB required)... "

if ! command -v free &> /dev/null; then
    echo -e "${RED}FAIL${NC}"
    echo "  Error: 'free' command not found."
    ((CHECKS_FAILED++))
else
    # Get total and used memory in GB
    MEM_TOTAL_KB=$(free -k | awk '/^Mem:/ {print $2}')
    MEM_USED_KB=$(free -k | awk '/^Mem:/ {print $3}')
    MEM_TOTAL_GB=$((MEM_TOTAL_KB / 1024 / 1024))
    MEM_USED_GB=$((MEM_USED_KB / 1024 / 1024))
    MEM_AVAILABLE_GB=$((MEM_TOTAL_GB - MEM_USED_GB))
    
    if [ "$MEM_TOTAL_GB" -ge "120" ]; then
        echo -e "${GREEN}PASS${NC}"
        echo "  Total Unified Memory: ${MEM_TOTAL_GB}GB"
        echo "  Used Memory: ${MEM_USED_GB}GB"
        echo "  Available Memory: ${MEM_AVAILABLE_GB}GB"
        
        # Check 24GB headroom guarantee
        if [ "$MEM_AVAILABLE_GB" -ge "24" ]; then
            echo "  ✓ 24GB headroom guarantee: PASS (${MEM_AVAILABLE_GB}GB available)"
            ((CHECKS_PASSED++))
        else
            echo -e "  ${YELLOW}⚠ 24GB headroom guarantee: WARN${NC}"
            echo "    Available: ${MEM_AVAILABLE_GB}GB (required: 24GB minimum)"
            echo "    System may experience memory pressure during operation."
            ((WARNINGS++))
            ((CHECKS_PASSED++))
        fi
    else
        echo -e "${RED}FAIL${NC}"
        echo "  Error: Insufficient unified memory detected."
        echo "  Required: 120GB minimum"
        echo "  Detected: ${MEM_TOTAL_GB}GB"
        echo "  DGX Spark GB10 should have 128GB unified memory."
        ((CHECKS_FAILED++))
    fi
fi
echo ""

# ============================================
# Check 3: Knowledge Harvester Dataset Directory
# ============================================
echo -n "Checking Knowledge Harvester dataset directory... "

DATASET_DIR="${VYASA_DATASET_DIR:-/raid/datasets}"
FALLBACK_DIR="/tmp/vyasa_datasets"

# Check primary location
if [ -d "$DATASET_DIR" ]; then
    if [ -w "$DATASET_DIR" ]; then
        echo -e "${GREEN}PASS${NC}"
        echo "  Dataset directory: $DATASET_DIR (writable)"
        ((CHECKS_PASSED++))
    else
        echo -e "${YELLOW}WARN${NC}"
        echo "  Warning: $DATASET_DIR exists but is not writable."
        echo "  System will fall back to: $FALLBACK_DIR"
        ((WARNINGS++))
        ((CHECKS_PASSED++))
    fi
else
    # Check if we can create it
    if mkdir -p "$DATASET_DIR" 2>/dev/null && [ -w "$DATASET_DIR" ]; then
        echo -e "${GREEN}PASS${NC}"
        echo "  Dataset directory: $DATASET_DIR (created and writable)"
        ((CHECKS_PASSED++))
    else
        echo -e "${YELLOW}WARN${NC}"
        echo "  Warning: Cannot create or write to $DATASET_DIR"
        echo "  System will use fallback: $FALLBACK_DIR"
        echo "  To fix: sudo mkdir -p $DATASET_DIR && sudo chmod 777 $DATASET_DIR"
        ((WARNINGS++))
        ((CHECKS_PASSED++))
    fi
fi
echo ""

# ============================================
# Check 4: Expertise Configuration File
# ============================================
echo -n "Checking for expertise configuration... "

EXPERTISE_FILE="data/private/expertise.json"

if [ -f "$EXPERTISE_FILE" ]; then
    echo -e "${GREEN}PASS${NC}"
    echo "  Found: $EXPERTISE_FILE"
    echo "  Using custom expert prompts."
    ((CHECKS_PASSED++))
else
echo -e "${YELLOW}WARN${NC}"
    echo "  Warning: $EXPERTISE_FILE not found."
    echo "  The system will use generic prompts instead of expert-tuned prompts."
    echo "  To enable expert prompts, create $EXPERTISE_FILE with your domain expertise."
    ((WARNINGS++))
    ((CHECKS_PASSED++))
fi
echo ""

# ============================================
# Check 5: Canonical service hostnames resolve
# ============================================
echo "Checking service hostnames (graph/vector/orchestrator)..."
SERVICE_ENDPOINTS=(
  "graph:8529:Graph (ArangoDB)"
  "vector:6333:Vector (Qdrant)"
  "orchestrator:8000:Orchestrator API"
)

for endpoint in "${SERVICE_ENDPOINTS[@]}"; do
  host="${endpoint%%:*}"
  rest="${endpoint#*:}"
  port="${rest%%:*}"
  label="${rest#*:}"
  echo -n "  ${label} @ ${host}:${port}... "
  if command -v nc >/dev/null 2>&1; then
    if nc -z "$host" "$port" >/dev/null 2>&1; then
      echo -e "${GREEN}REACHABLE${NC}"
      ((CHECKS_PASSED++))
    else
      echo -e "${YELLOW}WARN${NC}"
      echo "    Could not reach ${host}:${port} (may be offline). Verify after stack start."
      ((WARNINGS++))
    fi
  else
    echo -e "${YELLOW}SKIP${NC}"
    echo "    nc not available; skipping reachability test."
    ((WARNINGS++))
  fi
done
echo ""

# ============================================
# Check 6: Port Availability
# ============================================
echo "Checking port availability..."

PORTS_TO_CHECK=(
    "30000:Brain (Cortex)"
    "30001:Worker (Cortex)"
    "8529:Graph (ArangoDB)"
    "6333:Vector (Qdrant)"
    "8000:Orchestrator"
)

PORT_CONFLICTS=0

for PORT_INFO in "${PORTS_TO_CHECK[@]}"; do
    PORT=$(echo "$PORT_INFO" | cut -d: -f1)
    SERVICE=$(echo "$PORT_INFO" | cut -d: -f2)
    
    echo -n "  Port $PORT ($SERVICE)... "
    
    # Check if port is in use
    if command -v nc &> /dev/null; then
        # Using netcat (nc) if available
        if nc -z localhost "$PORT" 2>/dev/null; then
            echo -e "${RED}CONFLICT${NC}"
            echo "    Error: Port $PORT is already in use."
            echo "    Stop the conflicting service before launching Project Vyasa."
            ((PORT_CONFLICTS++))
            ((CHECKS_FAILED++))
        else
            echo -e "${GREEN}AVAILABLE${NC}"
            ((CHECKS_PASSED++))
        fi
    elif command -v ss &> /dev/null; then
        # Using ss (socket statistics) as fallback
        if ss -tuln | grep -q ":$PORT "; then
            echo -e "${RED}CONFLICT${NC}"
            echo "    Error: Port $PORT is already in use."
            echo "    Stop the conflicting service before launching Project Vyasa."
            ((PORT_CONFLICTS++))
            ((CHECKS_FAILED++))
        else
            echo -e "${GREEN}AVAILABLE${NC}"
            ((CHECKS_PASSED++))
        fi
    elif command -v lsof &> /dev/null; then
        # Using lsof as another fallback
        if lsof -i ":$PORT" &>/dev/null; then
            echo -e "${RED}CONFLICT${NC}"
            echo "    Error: Port $PORT is already in use."
            echo "    Stop the conflicting service before launching Project Vyasa."
            ((PORT_CONFLICTS++))
            ((CHECKS_FAILED++))
        else
            echo -e "${GREEN}AVAILABLE${NC}"
            ((CHECKS_PASSED++))
        fi
    else
        echo -e "${YELLOW}SKIP${NC}"
        echo "    Warning: Cannot check port (nc/ss/lsof not available)."
        echo "    Manually verify ports $PORT are free before launching."
        ((WARNINGS++))
    fi
done
echo ""

# ============================================
# Summary
# ============================================
echo "=========================================="
echo "Preflight Check Summary"
echo "=========================================="
echo "  Passed:  ${CHECKS_PASSED}"
echo "  Failed:  ${CHECKS_FAILED}"
echo "  Warnings: ${WARNINGS}"
echo ""

if [ "$CHECKS_FAILED" -eq "0" ]; then
    echo -e "${GREEN}✓ Launch Ready${NC}"
    echo ""
    echo "All critical checks passed. You can proceed with:"
    echo "  docker compose -f deploy/docker-compose.yml up -d"
    exit 0
else
    echo -e "${RED}✗ Launch Blocked${NC}"
    echo ""
    echo "Critical checks failed. Please resolve the issues above before launching."
    if [ "$PORT_CONFLICTS" -gt "0" ]; then
        echo ""
        echo "To find processes using conflicting ports:"
        echo "  sudo lsof -i :30000  # Brain"
        echo "  sudo lsof -i :30001  # Worker"
        echo "  sudo lsof -i :8529   # ArangoDB"
    fi
    exit 1
fi
