#!/usr/bin/env bash
# scripts/watchdog.sh - Observatory watchdog for DGX Spark
# Description : Polls observatory API and restarts services on degraded health.
# Dependencies: curl, docker, openssl
# Usage       : ./scripts/watchdog.sh
# [Decision] Credentials are auto-generated by default to prevent hardcoded leaks; users can override in deploy/.env.
set -euo pipefail

API_URL=${API_URL:-"http://localhost:8000/api/system/observatory"}
COMPOSE_FILE=${COMPOSE_FILE:-"$(dirname "$(dirname "${BASH_SOURCE[0]}")")/deploy/docker-compose.yml"}
TELEMETRY_FILE=${TELEMETRY_FILE:-"/raid/telemetry/events.jsonl"}

restart_logged=false

log_restart() {
  local reason=$1
  mkdir -p "$(dirname "$TELEMETRY_FILE")"
  echo "{\"event_type\":\"system_restart\",\"reason\":\"$reason\",\"timestamp\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" >> "$TELEMETRY_FILE" || true
  restart_logged=true
}

api_resp=$(curl -s --max-time 5 "$API_URL" || true)
if [[ -z "$api_resp" ]]; then
  echo "[watchdog] API unreachable"
  exit 0
fi

critical=$(echo "$api_resp" | jq -r '[.performance.status,.hardware.status,.quality.status,.context.status,.volume.status] | any(.=="critical")')
sglang_health=$(echo "$api_resp" | jq -r '.sources.sglang // "unknown"')
db_health=$(echo "$api_resp" | jq -r '.sources.db // "unknown"')
uma_pct=$(echo "$api_resp" | jq -r '.hardware.summary.uma_utilization_pct // 0')

# Restart SGLang stack on critical/perf degradation
if [[ "$critical" == "true" || "$sglang_health" == "degraded" || "$sglang_health" == "warning" ]]; then
  echo "[watchdog] Restarting cortex-worker and cortex-brain due to critical/sglang degradation"
  docker compose -f "$COMPOSE_FILE" restart cortex-worker cortex-brain || true
  log_restart "restart_sglang"
fi

# Restart graph DB if degraded
if [[ "$db_health" == "degraded" || "$db_health" == "warning" ]]; then
  echo "[watchdog] Restarting graph service due to db degradation"
  docker compose -f "$COMPOSE_FILE" restart graph || true
  log_restart "restart_graph"
fi

# UMA safety guard
uma_int=${uma_pct%.*}
if [[ "$uma_int" -gt 110 ]]; then
  echo "[watchdog] UMA utilization ${uma_pct}% > 110: restarting orchestrator"
  docker compose -f "$COMPOSE_FILE" restart orchestrator || true
  log_restart "restart_orchestrator_uma"
fi

if [[ "$restart_logged" == true ]]; then
  echo "[watchdog] Restart event logged to $TELEMETRY_FILE"
fi
